<?php

declare(strict_types=1);

// Checkers for the committed landing artifacts (resources/landing/*): they
// are GENERATED by apps/web scripts/build-landing.mjs from the contracts,
// and these tests re-derive them from contracts/ directly, so a hand edit or
// a stale regeneration fails the PHP suite as well ("vectors are law";
// design tokens are the only color source).

/**
 * @return array<string, mixed>
 */
function landingJson(string $name): array
{
    $raw = file_get_contents(resource_path('landing/'.$name));

    assert(is_string($raw));

    $data = json_decode($raw, true);

    assert(is_array($data));

    /** @var array<string, mixed> $data */
    return $data;
}

/**
 * @return array<string, mixed>
 */
function generateVector(string $id): array
{
    $raw = file_get_contents(dirname(base_path()).'/contracts/vectors/generate.v1.jsonl');

    assert(is_string($raw));

    foreach (explode("\n", $raw) as $line) {
        if (trim($line) === '') {
            continue;
        }

        $entry = json_decode($line, true);

        assert(is_array($entry));

        if ($entry['id'] === $id) {
            /** @var array<string, mixed> $entry */
            return $entry;
        }
    }

    throw new RuntimeException("vector {$id} not found");
}

test('hero.json is the certified vector gen-0014, verbatim', function (): void {
    $fixture = landingJson('hero.json');
    $vector = generateVector('gen-0014');

    expect($fixture['id'])->toBe('gen-0014');

    $board = $fixture['board'];

    assert(is_array($board));

    expect($board['rows'])->toBe($vector['rows'])
        ->and($board['cols'])->toBe($vector['cols'])
        ->and($board['breaks'])->toBe($vector['breaks'])
        ->and($board['spark'])->toBe(['r' => $vector['spark'][0], 'c' => $vector['spark'][1]])
        ->and($fixture['solution'])->toBe($vector['solution'])
        ->and($fixture['times'])->toBe($vector['times']);

    $expectedClues = array_map(
        fn (array $clue): array => ['r' => $clue['r'], 'c' => $clue['c'], 'm' => $clue['m']],
        $vector['clues'],
    );
    usort($expectedClues, fn (array $a, array $b): int => [$a['r'], $a['c']] <=> [$b['r'], $b['c']]);

    expect($board['clues'])->toBe($expectedClues);
});

test('strip.json is the certified vector gen-0049 with burnRamp colors', function (): void {
    $fixture = landingJson('strip.json');
    $vector = generateVector('gen-0049');

    expect($fixture['id'])->toBe('gen-0049')
        ->and($fixture['rows'])->toBe($vector['rows'])
        ->and($fixture['cols'])->toBe($vector['cols'])
        ->and($fixture['spark'])->toBe(['r' => $vector['spark'][0], 'c' => $vector['spark'][1]])
        ->and($fixture['solution'])->toBe($vector['solution'])
        ->and($fixture['times'])->toBe($vector['times']);

    $times = $vector['times'];

    assert(is_array($times));

    $maxMinute = max(array_map(intval(...), $times));
    expect($fixture['maxMinute'])->toBe($maxMinute);

    // Re-derive the colors from the frozen burnRamp formula
    // (contracts/design-tokens.json): c = from + (to - from) * f,
    // f = fMin + fSpan * (t / T).
    $tokens = json_decode(
        (string) file_get_contents(dirname(base_path()).'/contracts/design-tokens.json'),
        true,
    );

    assert(is_array($tokens) && is_array($tokens['burnRamp']));

    $ramp = $tokens['burnRamp'];
    $channel = function (string $hex, int $i): int {
        return (int) hexdec(substr($hex, 1 + $i * 2, 2));
    };
    $expected = [];

    for ($t = 0; $t <= $maxMinute; $t++) {
        $f = $ramp['fMin'] + $ramp['fSpan'] * ($t / $maxMinute);
        $rgb = [];

        for ($i = 0; $i < 3; $i++) {
            $a = $channel((string) $ramp['from'], $i);
            $b = $channel((string) $ramp['to'], $i);
            $rgb[] = (int) round($a + ($b - $a) * $f);
        }

        $expected[] = sprintf('rgb(%d, %d, %d)', $rgb[0], $rgb[1], $rgb[2]);
    }

    expect($fixture['colors'])->toBe($expected);
});

test('board.css carries every design token as a --bf-* variable', function (): void {
    $css = file_get_contents(resource_path('landing/board.css'));

    assert(is_string($css));

    $tokens = json_decode(
        (string) file_get_contents(dirname(base_path()).'/contracts/design-tokens.json'),
        true,
    );

    assert(is_array($tokens) && is_array($tokens['color']));

    foreach ($tokens['color'] as $name => $definition) {
        assert(is_array($definition) && is_string($definition['value']));

        $kebab = strtolower((string) preg_replace('/([a-z0-9])([A-Z])/', '$1-$2', $name));
        expect($css)->toContain("--bf-color-{$kebab}: {$definition['value']};");
    }

    expect($css)->toContain(':root {')
        ->toContain('--bf-font-body:')
        ->toContain('.bf-cell');
});

test('no raw hex colors outside the generated token block (CLAUDE.md rule 7)', function (): void {
    $views = glob(resource_path('views/landing/{,*/}*.blade.php'), GLOB_BRACE);

    assert(is_array($views));

    $views[] = resource_path('views/errors/404.blade.php');

    expect(count($views))->toBeGreaterThanOrEqual(7);

    foreach ($views as $view) {
        $source = file_get_contents($view);

        assert(is_string($source));

        expect(preg_match('/#[0-9a-fA-F]{3,8}\b/', $source))->toBe(
            0,
            basename($view).' contains a raw hex color; use var(--bf-*) from board.css',
        );
    }
});

test('the hero fixture is a Lookout 5×5 (the tier the hero promises)', function (): void {
    $fixture = landingJson('hero.json');
    $board = $fixture['board'];

    assert(is_array($board));

    expect($board['rows'])->toBe(5)->and($board['cols'])->toBe(5);
});
