// GENERATED from contracts/openapi.yaml by openapi-typescript — DO NOT EDIT.
// Regenerate: pnpm --filter @burnfront/api-client generate
// Freshness is CI-verified: pnpm --filter @burnfront/api-client generate:check
/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/auth/magic-link': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Request a sign-in link (constant response; throttled 3/h/email, 5/min/IP) */
    post: operations['requestMagicLink'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/auth/magic-link/consume': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Exchange a link token for a session (single use; session id rotated) */
    post: operations['consumeMagicLink'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/auth/logout': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** End the session */
    post: operations['logout'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/me': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Profile + progress summary */
    get: operations['getMe'];
    put?: never;
    post?: never;
    /** GDPR erasure — queued anonymization (profile erased, aggregates survive) */
    delete: operations['deleteMe'];
    options?: never;
    head?: never;
    /** Update profile preferences */
    patch: operations['updateMe'];
    trace?: never;
  };
  '/me/export': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** GDPR portability — queued; emailed signed URL (24h, single download) */
    get: operations['requestExport'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/me/import': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Anonymous→account merge (WS-20; anti-fabrication caps server-side)
     * @description Idempotent per item via `client_solve_id`. Every daily item is re-validated
     *     against the known board. Streak credit is capped at 7 days and only granted
     *     for dates whose boards were published before the claimed solve time.
     *     Imported solves are percentile-ineligible; rating seeds at half weight
     *     (RATING.md §5).
     */
    post: operations['importLocalRecord'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/me/solves': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Solve history (newest first, cursor-paged) */
    get: operations['listMySolves'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/me/streak': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Streak state (UTC semantics) */
    get: operations['getMyStreak'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/me/rating': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Fire Rating (Glicko-2 per RATING.md) */
    get: operations['getMyRating'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/daily/{date}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Daily metadata + embedded stats (one endpoint — decisions */
    get: operations['getDaily'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/daily/{date}/start': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Stamp the anti-cheat fetch anchor (idempotent; first stamp wins) */
    post: operations['startDaily'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/solves': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Submit a complete shading (idempotent via Idempotency-Key)
     * @description Validation is authoritative server-side (PHP BFS re-check; verdicts per
     *     contracts/vectors/README.md). `official_ms = min(client_ms, received_at −
     *     fetched_at)` and must be ≥ the replay duration and ≥ `n_breaks × 250`,
     *     otherwise the solve is stored valid-but-`suspect` (percentile-ineligible).
     *     Rate limit 30/min/user.
     */
    post: operations['submitSolve'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/events': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** First-party analytics (ADR-0008; anonymous allowed; 60/min/session) */
    post: operations['recordEvents'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/errors': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** First-party error beacon (sampled client-side; 10/min/session) */
    post: operations['recordFrontendError'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/health': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Liveness + content freshness */
    get: operations['health'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    Error: {
      error: {
        code: string;
        message: string;
      };
    };
    Me: {
      id: string;
      /** Format: email */
      email: string;
      timezone: string;
      /** @enum {string} */
      plan: 'free' | 'pro';
      /** Format: date-time */
      pro_until?: string | null;
      streak_alert_opt_in: boolean;
      streak: components['schemas']['Streak'];
      rating: components['schemas']['Rating'];
    };
    Position: [number, number];
    ClueDef: {
      r: number;
      c: number;
      m: number;
    };
    /** @description burnfront.puzzle/1 `board` object (contracts/schemas/puzzle.v1.json). */
    Board: {
      rows: number;
      cols: number;
      spark: components['schemas']['Position'];
      breaks: number;
      clues: components['schemas']['ClueDef'][];
    };
    Daily: {
      /** Format: date */
      date: string;
      incident_number: number;
      puzzle_id: string;
      /** @enum {string} */
      grade_tier: 'lookout' | 'crew' | 'hotshot';
      /**
       * Format: uri
       * @description Immutable CDN JSON (burnfront.puzzle/1).
       */
      content_url: string;
      /**
       * @description Pulled-daily streak amnesty (WS-18).
       * @default false
       */
      amnesty: boolean;
      stats: {
        solved_count: number;
        p50_ms?: number | null;
      };
      /** @description Present ONLY when the CDN-fallback flag is active. */
      puzzle?: components['schemas']['Board'];
    };
    HintCounts: {
      s1: number;
      s2: number;
      s3: number;
    };
    SolveSubmission: {
      /** @enum {string} */
      mode: 'daily' | 'pack' | 'endless';
      /** @description Required for daily/pack; absent for endless. */
      puzzle_id?: string;
      /** @description Required for endless; server re-validates with the PHP BFS (ADR-0006). */
      endless_spec?: components['schemas']['Board'];
      /** @description Row-major bit string, '1' = firebreak (vectors/README.md). */
      shaded: string;
      client_ms: number;
      /** Format: date-time */
      started_at: string;
      hints: components['schemas']['HintCounts'];
      undo_count: number;
      /** @description Gzipped event log [t_ms, cellIndex, mark]; retained 90 days (gdpr.md). */
      replay?: string;
      /** @description SHA-256 hex over the UNCOMPRESSED replay JSON bytes (ADR-0012 — server verifies after gunzip). REQUIRED whenever replay is present (ADR-0020). */
      replay_sha256?: string;
      /** @description REQUIRED for mode=endless, PROHIBITED for daily/pack (ADR-0020; enforced server-side) — client-graded chain length feeding the board prior (RATING.md §4). */
      deduction_steps?: number;
    };
    SolveResult: {
      solve_id: string;
      valid: boolean;
      /**
       * @description BurnVerdictReason (frozen order — vectors/README.md).
       * @enum {string}
       */
      reason?:
        | 'ok'
        | 'spark_shaded'
        | 'clue_shaded'
        | 'wrong_break_count'
        | 'unreachable_cell'
        | 'clue_time_mismatch';
      official_ms?: number | null;
      suspect: boolean;
      streak?: components['schemas']['Streak'];
      /** @description Glicko-2 update is queued (WS-08). */
      rating_pending?: boolean;
      daily?: {
        rank?: number | null;
        percentile?: number | null;
        solved_count?: number;
      };
    };
    SolveSummary: {
      solve_id: string;
      /** @enum {string} */
      mode: 'daily' | 'pack' | 'endless';
      puzzle_id?: string | null;
      /** Format: date */
      date?: string | null;
      incident_number?: number | null;
      valid: boolean;
      official_ms?: number | null;
      /** @description Zero hints. */
      clean?: boolean;
      /** Format: date-time */
      received_at: string;
    };
    Streak: {
      current: number;
      best: number;
      /** Format: date */
      last_daily_date?: string | null;
      /** @description One auto-freeze per calendar month (WS-07). */
      freeze_available?: boolean;
      /**
       * Format: date-time
       * @description UTC instant the streak dies if today stays unsolved.
       */
      safe_until?: string | null;
    };
    Rating: {
      rating: number;
      rd: number;
      volatility: number;
      games: number;
      /** @description True for the first 10 rated solves (RATING.md §5). */
      calibrating: boolean;
      /** @description Recent post-solve ratings, oldest first. */
      sparkline?: number[];
    };
    ImportItem: {
      /** Format: uuid */
      client_solve_id: string;
      /** @enum {string} */
      mode: 'daily' | 'endless';
      /**
       * Format: date
       * @description Daily items — the UTC incident date.
       */
      date?: string | null;
      shaded: string;
      client_ms: number;
      hints?: components['schemas']['HintCounts'];
      /** Format: date-time */
      solved_at: string;
    };
    ImportResult: {
      results: {
        /** Format: uuid */
        client_solve_id: string;
        /** @enum {string} */
        status:
          'credited' | 'duplicate' | 'invalid' | 'board_unknown' | 'date_ineligible' | 'stats_only';
      }[];
      credited_days: number;
      streak: components['schemas']['Streak'];
    };
    AnalyticsEvent: {
      /** @enum {string} */
      name:
        | 'first_seen'
        | 'tutorial_step'
        | 'solve_start'
        | 'solve_complete'
        | 'board_abandoned'
        | 'hint_used'
        | 'replay_watched'
        | 'share_clicked'
        | 'account_created';
      /** Format: date-time */
      ts: string;
      props?: {
        [key: string]: unknown;
      };
    };
  };
  responses: {
    /** @description No valid session. */
    Unauthenticated: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        'application/json': components['schemas']['Error'];
      };
    };
    /** @description Request shape rejected. */
    ValidationError: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        'application/json': components['schemas']['Error'];
      };
    };
    /** @description Throttled; retry after the indicated delay. */
    RateLimited: {
      headers: {
        'Retry-After'?: number;
        [name: string]: unknown;
      };
      content: {
        'application/json': components['schemas']['Error'];
      };
    };
  };
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  requestMagicLink: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': {
          /** Format: email */
          email: string;
        };
      };
    };
    responses: {
      /** @description Always returned for well-formed requests, account or not. */
      202: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      429: components['responses']['RateLimited'];
    };
  };
  consumeMagicLink: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': {
          token: string;
        };
      };
    };
    responses: {
      /** @description Session established (cookie set). */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Token invalid, expired, or already used. */
      410: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      429: components['responses']['RateLimited'];
    };
  };
  logout: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Session ended. */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      401: components['responses']['Unauthenticated'];
    };
  };
  getMe: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Profile + progress summary. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Me'];
        };
      };
      401: components['responses']['Unauthenticated'];
    };
  };
  deleteMe: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Anonymization queued; session ended. */
      202: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      401: components['responses']['Unauthenticated'];
    };
  };
  updateMe: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': {
          /** @description IANA zone; streak-risk email send time only (ADR-0002) */
          timezone?: string;
          /** @description Double opt-in starts on true (WS-21) */
          streak_alert_opt_in?: boolean;
        };
      };
    };
    responses: {
      /** @description Updated profile. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Me'];
        };
      };
      401: components['responses']['Unauthenticated'];
    };
  };
  requestExport: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Export queued; link arrives by email. */
      202: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      401: components['responses']['Unauthenticated'];
      429: components['responses']['RateLimited'];
    };
  };
  importLocalRecord: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': {
          items: components['schemas']['ImportItem'][];
        };
      };
    };
    responses: {
      /** @description Per-item results + credited summary. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ImportResult'];
        };
      };
      401: components['responses']['Unauthenticated'];
      429: components['responses']['RateLimited'];
    };
  };
  listMySolves: {
    parameters: {
      query?: {
        cursor?: string;
        limit?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Newest-first solve history. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            items: components['schemas']['SolveSummary'][];
            next_cursor?: string | null;
          };
        };
      };
      401: components['responses']['Unauthenticated'];
    };
  };
  getMyStreak: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Streak state (UTC semantics). */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Streak'];
        };
      };
      401: components['responses']['Unauthenticated'];
    };
  };
  getMyRating: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Fire Rating (Glicko-2 per RATING.md). */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Rating'];
        };
      };
      401: components['responses']['Unauthenticated'];
    };
  };
  getDaily: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description UTC day */
        date: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /**
       * @description Board content normally lives on the CDN (`content_url`); `puzzle` is
       *     embedded only when the origin fallback flag is active (CDN outage).
       */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Daily'];
        };
      };
      /** @description No incident published for this date (incl. future dates). */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  startDaily: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        date: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Fetch anchor recorded. */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      401: components['responses']['Unauthenticated'];
      /** @description No incident for this date. */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  submitSolve: {
    parameters: {
      query?: never;
      header: {
        /** @description Client-generated UUID, MUST be version 7 (enforced server-side, ADR-0021); doubles as `client_solve_id`. */
        'Idempotency-Key': string;
      };
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['SolveSubmission'];
      };
    };
    responses: {
      /** @description Idempotent replay — the stored original response. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['SolveResult'];
        };
      };
      /** @description First acceptance of this key. */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['SolveResult'];
        };
      };
      401: components['responses']['Unauthenticated'];
      422: components['responses']['ValidationError'];
      429: components['responses']['RateLimited'];
    };
  };
  recordEvents: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': {
          anon_id: string;
          events: components['schemas']['AnalyticsEvent'][];
        };
      };
    };
    responses: {
      /** @description Accepted (fire-and-forget). */
      202: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      422: components['responses']['ValidationError'];
      429: components['responses']['RateLimited'];
    };
  };
  recordFrontendError: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': {
          message: string;
          stack?: string;
          route?: string;
        };
      };
    };
    responses: {
      /** @description Filed. */
      202: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      429: components['responses']['RateLimited'];
    };
  };
  health: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Liveness + content freshness snapshot (WS-18 alerts read this). */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            ok: boolean;
            tomorrow_published: boolean;
          };
        };
      };
      429: components['responses']['RateLimited'];
      /** @description Degraded — a dependency is down. */
      503: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Error'];
        };
      };
    };
  };
}
